#!/usr/bin/env bash

set -euo pipefail

flags=(
    "-DDEBUG_BOUNDS_CHECK"
    "-DDEBUG_PRINT_VM"
    "-fanalyzer"
    "-fshort-enums"
    "-g"
    "-march=native"
    "-O1"
    "-static"
    "-std=c99"
    "-Wall"
    "-Wcast-align"
    "-Wcast-align=strict"
    "-Wcast-qual"
    "-Wconversion"
    "-Wdate-time"
    "-Wdouble-promotion"
    "-Wduplicated-branches"
    "-Wduplicated-cond"
    "-Werror"
    "-Wextra"
    "-Wfatal-errors"
    "-Wfloat-equal"
    "-Wformat-signedness"
    "-Wformat=2"
    "-Winline"
    "-Wlogical-op"
    "-Wmissing-declarations"
    "-Wmissing-include-dirs"
    "-Wmissing-prototypes"
    "-Wnull-dereference"
    "-Wpacked"
    "-Wpedantic"
    "-Wpointer-arith"
    "-Wredundant-decls"
    "-Wshadow"
    "-Wstack-protector"
    "-Wstrict-prototypes"
    "-Wswitch-enum"
    "-Wtrampolines"
    "-Wundef"
    "-Wunused"
    "-Wunused-macros"
    "-Wwrite-strings"
)

now () {
    date +%s.%N
}

(
    for x in "$WD"/src/*.h; do
        cppcheck "$x"
    done
    cppcheck \
        --enable=all \
        --suppress=missingIncludeSystem \
        "$WD/src"
    clang-format -i -verbose "$WD/src"/*.c
    clang-format -i -verbose "$WD/src"/*.h
)

(
    start=$(now)
    gcc "${flags[@]}" -o "$WD/bin/main" "$WD/src/main.c"
    end=$(now)
    python3 -c "print(\"Compiled! ({:.3f}s)\".format(${end} - ${start}))"
)

"$WD/bin/main" || echo "$?"
