#!/usr/bin/env bash

set -euo pipefail

lib="$WD/src/lib"
flags=(
    "-DDEBUG_BOUNDS_CHECK"
    "-DDEBUG_PRINT_VM"
    "-fanalyzer"
    "-fshort-enums"
    "-fsingle-precision-constant"
    "-g"
    "-I$lib"
    "-march=native"
    "-O1"
    "-static"
    "-std=c99"
    "-Wall"
    "-Wcast-align"
    "-Wcast-align=strict"
    "-Wcast-qual"
    "-Wconversion"
    "-Wdate-time"
    "-Wdouble-promotion"
    "-Wduplicated-branches"
    "-Wduplicated-cond"
    "-Werror"
    "-Wextra"
    "-Wfatal-errors"
    "-Wfloat-equal"
    "-Wformat-signedness"
    "-Wformat=2"
    "-Winline"
    "-Wlogical-op"
    "-Wmissing-declarations"
    "-Wmissing-include-dirs"
    "-Wmissing-prototypes"
    "-Wnull-dereference"
    "-Wpacked"
    "-Wpedantic"
    "-Wpointer-arith"
    "-Wredundant-decls"
    "-Wshadow"
    "-Wstack-protector"
    "-Wstrict-prototypes"
    "-Wswitch-enum"
    "-Wtrampolines"
    "-Wundef"
    "-Wunused"
    "-Wunused-macros"
    "-Wwrite-strings"
)

now () {
    date +%s.%N
}

(
    cppcheck "-I$lib" --enable=all --suppress=missingIncludeSystem "$WD/src"
    clang-format -i -verbose "$WD/src/"*/*
)

(
    start=$(now)
    gcc "${flags[@]}" -o "$WD/bin/vm_test" "$WD/src/app/vm_test.c"
    gcc "${flags[@]}" -o "$WD/bin/demo" "$WD/src/app/demo.c"
    end=$(now)
    python3 -c "print(\"Compiled! ({:.3f}s)\".format(${end} - ${start}))"
)

"$WD/bin/vm_test"
"$WD/bin/demo" "$WD/out/demo.sal" || echo "$?"
